### PR TITLE
Enable nightly STF 1.5

### PR DESCRIPTION
**Pull request by leifmadsen**

### CODE REVIEW

**Comment by leifmadsen** [comment]
Tested builds via workflow trigger at https://github.com/infrawatch/release-automation/actions/runs/3584623632

**Comment by leifmadsen** [comment]
Haha oops I tested this against the current `stable-1.5` branch which doesn't have the metadata changes landed, so it'll build against unstable. I guess this is a good test, because now I can re-run the job after merging the metadata changes and see the channel get updated from `unstable` to `stable-1.5` on the 1.5 build.

**Comment by jparker-rh** [comment]
LGTM

**Review by jparker-rh — APPROVED** [review]

**Review by csibbitt — APPROVED** [review]

**Comment by leifmadsen** [comment]
Re-ran the job after merging the metadata update changes for STO and SGO. Everything looks good, and separate bundles and index images are created in quay.io, so I'm satisfied with this. I will be doing another general deployment run against these artifacts and will come back with any further changes/fixes if necessary.

**Pull request merged**
